### ISSUE TITLE
PHP Fatal error:  Uncaught Viessmann\API\ViessmannApiException: Unable to get data for feature heating.sensors.temperature.outside

### ISSUE THREAD

**Issue by JungeG** [thetrueavatar/Viessmann-Api#11]
Hi Claude,
since 2 hours a get error messages like this:

>  php GetOutsideTemperature.php
PHP Fatal error:  Uncaught Viessmann\API\ViessmannApiException: Unable to get data for feature heating.sensors.temperature.outside
Reason: DEVICE_COMMUNICATION_ERROR in phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/API/ViessmannAPI.php:790
Stack trace:
#0 phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/API/ViessmannAPI.php(60): Viessmann\API\ViessmannAPI->getEntity('heating.sensors...')
#1 /etc/openhab2/scripts/viessmann/GetOutsideTemperature.php(4): Viessmann\API\ViessmannAPI->getOutsideTemperature()
#2 {main}
  thrown in phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/API/ViessmannAPI.php on line 790

No matter which method I call it seems to be also line 790.
Don't know how to fix this.
Thanks for an hint.
Georg

**Comment by thetrueavatar** [comment]
Viessman server just say: DEVICE_COMMUNICATION_ERROR
I can't help you cause it's a problem from the viessmann server. It could
just be that your vitoconnect isn't connected anymore but I have already
had the same error while vitoconnect was correctly connected. it's just a
server problem that should be solved by itself...
Best Regards,
thetrueavatar

Le 26 nov. 2018 4:08 PM, "JungeG" <notifications@github.com> a écrit :

Hi Claude,
since 2 hours a get error messages like this:

php GetOutsideTemperature.php
PHP Fatal error: Uncaught Viessmann\API\ViessmannApiException: Unable to
get data for feature heating.sensors.temperature.outside
Reason: DEVICE_COMMUNICATION_ERROR in
phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/API/ViessmannAPI.php:790
Stack trace:
#0
phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/API/ViessmannAPI.php(60):
Viessmann\API\ViessmannAPI->getEntity('heating.sensors...')
#1 <https://github.com/thetrueavatar/Viessmann-Api/issues/1>
/etc/openhab2/scripts/viessmann/GetOutsideTemperature.php(4):
Viessmann\API\ViessmannAPI->getOutsideTemperature()
#2 <https://github.com/thetrueavatar/Viessmann-Api/issues/2> {main}
thrown in
phar:///etc/openhab2/scripts/viessmann/Viessmann-Api-0.4-SNAPSHOT.phar/src/API/ViessmannAPI.php
on line 790

No matter which method I call it seems to be also line 790.
Don't know how to fix this.
Thanks for an hint.
Georg

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/thetrueavatar/Viessmann-Api/issues/11>, or mute the
thread

**Comment by thetrueavatar** [comment]
Guess who had the very same error 😀 ? I have just saw in my jeedom log it
happened at 2018-11-26 13:49:38. Right now I don't have the problem
anymore...

**Comment by JungeG** [comment]
You are right, right now it seems to be solved
Thanks Georg
