### ISSUE TITLE
Steuerung der Heizung

### ISSUE THREAD

**Issue by OMCastle** [thetrueavatar/Viessmann-Api#15]
Ich würde mich über folgende Funktionen freuen. 

1) Aktivieren der Warmwasseraufbereitung für 15 min um einmal den Warmwasserspeicher zu füllen 
2) Änderung der Temperatur für die Heizung

Entweder direkt als Funktionen oder über direktes „schreiben“ der Variablen.

**Comment by rogrun** [comment]
Hallo OMCastle,

ich möchte auch sehr gern den Warmwasserspeicher über das Script füllen. Hast du das hin bekommen?

Gruß rogrun

**Comment by thetrueavatar** [comment]
Hello,
I'm not quite sure to understand what you want. Since version 1.0.1 all feature exposed by viessmann are exposed(in read and write). You'll find every method implemented on the api documentation here:
https://htmlpreview.github.io/?https://raw.githubusercontent.com/thetrueavatar/Viessmann-Api/develop/docs/class-Viessmann.API.ViessmannAPI.html

**Comment by rogrun** [comment]
Hello,

i want to charge my boiler once. But i don't know how to do this. Can you tell me which method i have tu use?

Thanks alot

**Comment by thetrueavatar** [comment]
By once you mean a one shot ? TBH I only charge my boiler 15 every morning.
It's enough for me to keep hot wate>50° during the whole day.
However I have the exact same problem in fact because sometimes my wife
want to take a shower and she complains the water is not hot enough. I have
already tought about using a buton to ask on demand water heating.
However, there is no way with viessmann service to ask "on demand" hot
water from what I have seen. There is a program for heating to force it no
matter the schedule but not for dhw...
 You have to schedule it and unschedule it.
You can obtain the schedule with getDhwSchedule()
You'll get a json that represents schedule. Here is a sample:

{
  "mon": [
    {
      "start": "03:00",
      "end": "24: 00",
      "mode": "on",
      "position": 1
    }
  ],
  "tue": [
    {
      "start": "03:00",
      "end": "24: 00",
      "mode": "on",
      "position": 3
    }
  ],
  "wed": [
    {
      "start": "02:00",
      "end": "24: 00",
      "mode": "on",
      "position": 2
    }
  ],
  "thu": [
    {
      "start": "03:00",
      "end": "24: 00",
      "mode": "on",
      "position": 0
    }
  ],
  "fri": [
    {
      "start": "03:00",
      "end": "24: 00",
      "mode": "on",
      "position": 4
    }
  ],
  "sat": [
    {
      "start": "03:00",
      "end": "24: 00",
      "mode": "on",
      "position": 0
    }
  ],
  "sun": [
    {
      "start": "03:00",
      "end": "24: 00",
      "mode": "on",
      "position": 0
    }
  ]
}

The problem, is that you can't add something in the current schedule so you
have to add the range of heating to the existing schedule overwritte it
with the new schedule by using the setRawDhwSchedule...
I have check on the ViCare APP and that's what they do...
That requires some coding work unfortunately and since my api is stateless
you'll have to erase the added schedule.
Maybe there is another way to achieve your goal but can't see it tbh.
Best Regards,

**Comment by rogrun** [comment]
I have found this Coder here: [https://forum.fhem.de/index.php/topic,86073.195.html](https://forum.fhem.de/index.php/topic,86073.195.html)
________________________________________________________________
#!/bin/bash
export CLIENTID=79742319e39245de5f91d15ff4cac2a8
export CLIENTSECRET=8ad97aceb92c5892e102b093c7c083fa
export TOKEN_EP=https://iam.viessmann.com/idp/v1/token
export AUTHZ_EP=https://iam.viessmann.com/idp/v1/authorize
export SCOPE=openid
export REDIRECTURI=vicare://oauth-callback/everest
export isiwebuserid=user
export isiwebpasswd=pw
CODE=`curl -s -k --user "$isiwebuserid:$isiwebpasswd" "$AUTHZ_EP?client_id=$CLIENTID&scope=$SCOPE&redirect_uri=$REDIRECTURI&response_type=code"| grep -Eio 'code=(.)*"'|  cut -c"6-" | sed 's/.$//'`
#echo "CODE=$CODE"
TOKEN=`curl -s -k --user "$CLIENTID:$CLIENTSECRET" -d "code=$CODE&grant_type=authorization_code&client_id=$CLIENTID&redirect_uri=$REDIRECTURI" $TOKEN_EP | sed 's/{"access_token":"//' | sed 's/".*//'`
#REP_STATUS=`curl -k -H "AUTHORIZATION: Bearer $TOKEN" "https://api.viessmann-platform.io/operational-data/installations/votre_numero/gateways/votre_numero/devices/0/features/heating.circuits.0.operating.modes.active?expanded=false&"`
#echo "$REP_STATUS"
REP=`curl -X POST  https://api.viessmann-platform.io/operational-data/installations/xxxx/gateways/xxxxxxxxxx/devices/0/features/heating.dhw.oneTimeCharge/activate -S -s -H "Content-Type: application/json" -H "AUTHORIZATION: Bearer $TOKEN" -d '{"mode":"activate"}'`
echo "$REP"
_________________________________________________

Is it possible to implement it in your API?

**Comment by rogrun** [comment]
Hello,

i have found a way to start the OneTimeCharge.
You only need to enable it with the "setRawJsonData" function as follows:

```
<?php
include __DIR__ . '/bootstrap.php';
$mode = "{\"mode\": \"activate\"}";

$viessmannApi->setRawJsonData("heating.dhw.oneTimeCharge", "activate", $mode);
```

And this code to deactivate:
```
<?php
include __DIR__ . '/bootstrap.php';
$mode = "{\"mode\": \"deactivate\"}";

$viessmannApi->setRawJsonData("heating.dhw.oneTimeCharge", "deactivate", $mode);
```

Best regards

**Comment by thetrueavatar** [comment]
Hello,
Thank you for the feedback !
I tought that the one time charged was only for external electrical
heating. Do you mean that it allows you to start hot water with regular
heating system ?
Best Regards,

**Comment by thetrueavatar** [comment]
I will add a function to enable/disable OneTimeCharge.
I have implemented a function to test if it's enable but didn't know how to
start and stop it.
Thanks to your feedback I will has such function.

**Comment by thetrueavatar** [comment]
I have implemented a startOneTimeCharge and stopOneTimeCharge but since I
don't have the feature I can't test it.
May I ask you to test those 2 new functions please ?
Best Regards

**Comment by rogrun** [comment]
Now i have it tested. The OneTimeCharge is starting on my heatingsystem, but i get this message in the browser:

> Message: Return value of Viessmann\API\ViessmannAPI::startOneTimeDhwCharge() must be of the type string, null returned Code: 0

Here my code:
```
<?php
include __DIR__.'/bootstrap.php';
$viessmannApi->startOneTimeDhwCharge();

echo "OneTimeCharge is: ".$viessmannApi->isOneTimeDhwCharge();
```

The same message, when I'm stopping the OneTimeCharge:

> Message: Return value of Viessmann\API\ViessmannAPI::stopOneTimeDhwCharge() must be of the type string, null returned Code: 0


Here are details from my heating:
Viessmann Vitodens 300-W B3HB
Viessmann Vitocell 100-W

**Comment by rogrun** [comment]
I think the code in ViessmannAPI should be:

```
public function isOneTimeDhwCharge(): bool
    {
        return $this->getEntity(ViessmannFeature::HEATING_DHW_ONETIMECHARGE)->getProperty("active")["value"];
    }

    public function startOneTimeDhwCharge()
    {
        $data = "{\"mode\": \"activate\"}";
        return $this->setRawJsonData(ViessmannFeature::HEATING_DHW_ONETIMECHARGE, "activate", $data);
    }

    public function stopOneTimeDhwCharge()
    {

        $data = "{\"mode\": \"deactivate\"}";
        return $this->setRawJsonData(ViessmannFeature::HEATING_DHW_ONETIMECHARGE, "deactivate", $data);
    }
```

But its not tested

**Comment by thetrueavatar** [comment]
Indeed I didn't checked method signature and added string return which had
no sens for "write" method...
I have fixed it and change string type to bool type for isOneTimeDhwCharge.
Please be aware you have to cast it into int while displaying value with
echo such as this "echo (int)$viessmannApi->isOneTimeDhwCharge();"
Thanks for your feedback

**Comment by rogrun** [comment]
Thank you for your great work. Now it works fine. 
I took some changes in the example/StartOneTimeCharge.php

Here is my file to start:

``` 
<?php
include __DIR__.'/bootstrap.php';
$viessmannApi->startOneTimeDhwCharge();
sleep(1);
echo (int)$viessmannApi->isOneTimeDhwCharge();
```

I have add the `sleep(1);` for waiting a short time, so that the OneTimeCharge at my heating can start. After that waiting I get a response from API that the OneTimeCharge runs or not. 

Best regards

**Comment by thetrueavatar** [comment]
Hello,
Somebody reports me that he has trouble with startOneTimeDhwCharge(). Since
I you did the test on june could you check if it's still working ?
Best Regards,

**Comment by shikousa** [comment]
Is the startOneTimeDhwCharge() working reliable? I'm not sure what the correct call is. In StartOneTimeCharge.php you call the startOneTimeDhwCharge() twice, whereas @rogrun calls it once, but has a delay of 1s before getting the status? Thanks.

**Comment by rogrun** [comment]
Hello, it is not nessesary to call it twice. In my use case, I call startOneTimeDhwCharge () once and wait a second to query whether it ran successfully.

I start OneTimeCharge in one PHP and query the status in another. This means that the methods are not executed via the cache.

Best regards

**Comment by shikousa** [comment]
Hello. I could also make startOneTimeDhwCharge() working now, but the script always returns 0. Even if I have a delay of 5s, it returns 0.

StartOneTimeCharge.php:

```
<?php
include __DIR__.'/bootstrap.php';
$viessmannApi->startOneTimeDhwCharge();
sleep(5);
echo (int)$viessmannApi->isOneTimeDhwCharge();
```


Once I call another script right after startOneTimeDhwCharge() to only get the status of isOneTimeDhwCharge() it is working.
Is there some kind of caching?

StatusOneTimeCharge.php
```
<?php
include __DIR__.'/bootstrap.php';
echo (int)$viessmannApi->isOneTimeDhwCharge();
```

**Comment by rogrun** [comment]
Hello, you have to call the request in each single php, because since the API is limited from Viessmann-Server last year, all requests in this API are cached. So this Code will failed:

> <?php
include __DIR__.'/bootstrap.php';
$viessmannApi->startOneTimeDhwCharge();
sleep(5);
echo (int)$viessmannApi->isOneTimeDhwCharge();
