### ISSUE TITLE
DHW OneTimeCharge returns error

### ISSUE THREAD

**Issue by rogrun** [thetrueavatar/Viessmann-Api#19]
Hello,

when I start the dhwOneTimeCharge i got this error:

> Message: Unable to set data for featureheating.dhw.oneTimeCharge and action activate and data{"mode": "activate"} Reason: Unsupported Media Type Code: 1
> 

do you know how to fix it?

EDIT: There is a general problem with all function that uses the setRawJsonData function.

Best regards 
rogrun

**Comment by rogrun** [comment]
The version 1.2.0-SNAPSHOT fixes this issue

Thanks

**Comment by thetrueavatar** [comment]
Sorry I didn't had the time to answer you. The first fix was wrong and so I
had to remove the "Accept" header because it was  enforced to "
application/vnd.siren+json
<https://github.com/thetrueavatar/Viessmann-Api/commit/07a536ddf299f4f1c0b8db588ba1965971cd7122>".
this is waht was causing some issue for "setter" methods.
Regards,
Claude

**Comment by rogrun** [comment]
No problem. Yesterday evening it was late. But today in the morning i have found after some search in the code that issue with the accepted header. And then i have seen that a new snapshot is online.
