### ISSUE TITLE
english explanation

### ISSUE THREAD

**Issue by alwashe** [thetrueavatar/Viessmann-Api#2]
hi, is there an english explanation?

**Comment by thetrueavatar** [comment]
not yet but I will provide one as soon as I found how to  internationalize
it. the problem is is that people living in France (I'm living in
Belgium)doesn't speak English at all . So I have to provide at least one
French translation.so I hope to find a way to provide English and French
translation together

**Comment by thetrueavatar** [comment]
I have quickly translated the documentation in the README-en.md available
here :
https://github.com/thetrueavatar/Viessmann-Api/blob/develop/README-en.md
and on the wiki here :
https://github.com/thetrueavatar/Viessmann-Api/wiki/english
Best Regards,

**Comment by thetrueavatar** [comment]
Translation done
