### ISSUE TITLE
GetSupplyProgramTemperature.php returning no Value

### ISSUE THREAD

**Issue by JungeG** [thetrueavatar/Viessmann-Api#23]
Hi,
I used this php to read the temperature - it was working until recently. When I call the method it returns:

> Message: Property "value" was not found.
Code: 1

any idea what happened?
I have attached the GetAllFeatures.php results as txt-file.
[allfeatures.txt](https://github.com/thetrueavatar/Viessmann-Api/files/3667537/allfeatures.txt)

Thanks for help
Georg

**Comment by thetrueavatar** [comment]
I have been reported this problem from other people. However, it just
viessmann's server which stop sending the information(some people get
DEVICE COMMUNICATION ERROR or and empty response such as you).
Are you able to get this information with the ViCare app ? Since I don't
have this feature I can't test if they have changedms+
 the way of getting this information ... I have check in the source code of
the ViCare application but didn't find any change.
Viessmann is updating frequently its services but sometimes breaks its own
feature.
Regards,
Claude

**Comment by JungeG** [comment]
Thanks Claude for the quick response.
I have searched in ViCare - but didn't find the value for SupplyProgramTemperature.
Did you see the info in the AllFeatures.txt.
If the value can't be retrieved anymore I will close the issue.
Georg

**Comment by thetrueavatar** [comment]
Viessman's server is supposed to return a response like this:

"properties": {
  "value": {
    "type": "number",
    "value": 58
  },
  "status": {
    "type": "string",
    "value": "connected"
  }
}


However your response doesn't have any  "value" field in the "properties"
section and the status is "notConnected":

"properties": {
  "status": {
    "type": "string",
    "value": "notConnected"
  }
}

I don't think it's a problem with your installation since other user of the
api have the same problem.
Regards,

**Comment by JungeG** [comment]
It seems that the problem is with Viessmann directly - see above.
