### ISSUE TITLE
Notice on API use – Viessmann Developer Portal

### ISSUE THREAD

**Issue by JungeG** [thetrueavatar/Viessmann-Api#30]
Hi Claude!
You probably have seen following mail:

 _Dear
{{ insert first_name 'default=default' }} {{ insert last_name 'default=default' }},
 
an
 evaluation has shown that you have used the web interface to Viessmann IoT Services very frequently in recent days.
 
On
 the one hand, we are delighted to know you are taking a closer look at our products and solutions. Especially since you have (apparently) found a solution for your specific use case without a description or our support from our side.
On
 the other hand, it challenges us to check and channel the method and frequency of requests to our IoT Services in order to keep those stable and available for all our users.
 
That’s
 why we have now taken the decision to limit access to our API. From the coming week on, a threshold will become active that prevents from unauthorized use of the API.
 This will affect all third-party solutions, which can thereby no longer be used.
 
We
 are aware that the demand for APIs to our technologies for integration into other solutions and third-party systems is increasing. To provide you with an opportunity for this, we will launch a portal
in the next two
 months for all developers to get access
 to our API. With the Viessmann Developer Portal, we intend to open ourselves up, release a documentation of the interface and co-develop new solutions together with you. In addition, we are planning to provide you with useful information around
 our heating systems you need for your development and to offer you a first-level support concerning our APIs.
 
As one of the users who is already working with our API, we would like to invite you to an early access to the Developer Portal. If you are interested, please fill out this
 short form. The access to the pre-version of the Portal will be sent to you within the next weeks.
 
We
 hope you understand the decision that we have to take. If you are interested to support us, on further development on the API and to explore new possibilities, we are very happy to welcome you to our Developer Portal soon!
 
In
 the meantime in case you have any questions, feel free to contact us under  developer@viessmann.com.
 
Thank
 you for your understanding.
 
All
 the best!
 
Your
 Viessmann Developer Portal Team_

Are you changing your scripts, that we can use it in future?
Kind regards 
Georg

**Comment by thetrueavatar** [comment]
No but I have seen someone else complaining about this on the viessman
community website:
https://www.viessmann-community.com/t5/Experten-fragen/ViCare-Blick-zur%C3%BCck-und-nach-vorne/qaq-p/84614/comment-id/103306#
I guess that's a side effect of their current dev on the new official API.
I guess they are monitoring their current api and activate some
threshold where they'll consider that too many connection could be a DDOS
attack.
You should check your cron trigger that get the data and see if you may
increase the polling interval.
Regards,

Le ven. 13 mars 2020 à 20:32, Georg Jungermann <notifications@github.com> a
écrit :

**Comment by thetrueavatar** [comment]
Here is someone for openhab who explain that viessman sent an email to explain they will activate a treshold for non official third party client. 

> From the coming week on, a threshold will become active that prevents from unauthorized use of the API. This will affect all third-party solutions, which can thereby no longer be used.
We are aware that the demand for APIs to our technologies for integration
into other solutions and third-party systems is increasing.
To provide you with an opportunity for this, we will launch a portal in the next two months for all developers to get access to our API. With the Viessmann Developer Portal , we intend to open ourselves up, release a documentation of the interface and co-develop new solutions together with you

**Comment by silverback658** [comment]
Hi, 
I hope you are right and they are just being prudent but the tone of the mail seems to suggest otherwise and it give me the feeling that Viessmann wants to take control back. 
Also the 'threshold' mentioned sounds like a translation glitch and as the meaning is clearer in the following sentence, where they state that third party solutions won't work anymore. 
As for their 'public' API, it could have a price attached to it - rather questionable considering it is our data - and on the other hand, judging from the ViCare app (meh), I wouldn't be surprised if it will turn out to be just a limited subset.
I would have to go through the documents to infer what data I have implicitly signed off to them and what GDPR has to say about it. 
I am by far no expert, as I have just started looking into this as a 'project' to get back into coding (also driven by the frustration caused by the poor access to data), but alternative solutions gathering the data locally before being sent may be better, particularly if they rely on technology used by larger companies that Viessmann cannot afford to disappoint.
A small web server on the VitoConnect providing local connectivity would be great ...

Michele

**Comment by JungeG** [comment]
There are actual versions released to cope with the threshold issue.
