### ISSUE TITLE
Viessmann published advice to change the endpoint 

### ISSUE THREAD

**Issue by JueBag** [thetrueavatar/Viessmann-Api#54]
Bonjour,

I guess you (@thetrueavatar ) have also recieved to mail from Viessmann.

Are you going to implement to adviced change for the new [endpoint](https://iam.viessmann.com/idp/v2/authorize)?

Tried to do the needed change (changing from v1 to v2 in 2 files), however when trying to create a .phar I got only  errors.

**Comment by thetrueavatar** [comment]
No I won't. The main reason of my project was to provide an easy client to
consume data provided through the private  API behind vicare.
Since this api was not designed for home automation but for smartphone app
navigation I have implemented such a client base on my reverse engineering
of the ViCare service api.
Calling it an API as a mistake I have done, It's really just a client.
With an official API that is designed for home-automation I hope they will
provide an official API contract. OpenAPI is the standard to define in yaml
those kind of contract.
With this kind of file, client can be generate easealy with a lot of tools
without the need to write custom code.
So my client is obviously no longer of any relevance.
Regards

Le ven. 19 févr. 2021 à 10:43, Jürgen Baginski <notifications@github.com> a
écrit :

**Comment by thetrueavatar** [comment]
That's for the middle term plan.
I will adapt the part for the current vicare api of course.
Regards,


Le ven. 19 févr. 2021 à 15:13, thetrueavatar <thetrueavatar@gmail.com> a
écrit :

**Comment by JueBag** [comment]
Thanks!
Don't know why I failed creating the .phar by myself!

**Comment by thetrueavatar** [comment]
For information, I have updated the develop branch(1.4.0-SNAPSHOT) to use
the v2 of the service.
For the 2 provided url, currently it doesn't work(permission denied). I
suspect this is a part of the new api(iot is in the url...) and so the
client_id-secret from ViCare has more than likely no grant for this.
I'm waiting to get my access to test this.
Regards,

Le ven. 19 févr. 2021 à 15:22, Jürgen Baginski <notifications@github.com> a
écrit :

**Comment by JueBag** [comment]
> For the 2 provided url, currently it doesn't work(permission denied).

So, the manner of publishing anything by Viessmann  hasn't changed. Big announcements, always late, errors are common....

**Comment by thetrueavatar** [comment]
Switch done to new endpoint

**Comment by JueBag** [comment]
Merci Beacoup.
Is it also working now (from the Viessmann side?) or is only your code part done?

[Edit:] It's working here!

**Comment by thetrueavatar** [comment]
After some more testing it's working when I'm doing it manually. So this is
related to with the way I manage to do the call in my code.
Regards

Le sam. 20 févr. 2021 à 11:37, Jürgen Baginski <notifications@github.com> a
écrit :

**Comment by JueBag** [comment]
I had no problem running the calls with the new .phar ( the only thing to remember was changing the the bootstrap.php to the new name).
