### ISSUE TITLE
from yesterday - Error during authentication process

### ISSUE THREAD

**Issue by dr-boss** [thetrueavatar/Viessmann-Api#69]
Message: Error during authentication process. Please review your username/password
Code: 0
Message: response didn't contains code to get token probably due to an error in authentication process. Response :
Code: 0

The standard app for Android from Viessmann work fine. I login without problem with my user/pass on https://developer.viessmann.com/en/clients. The ClientID is same in config and on page.

**Comment by thetrueavatar** [comment]
don't have this problem so can't help unless you provide me the version of the api and if  the error is coming since you have update it.
BTW, I did a fix in the latest version of the api. Befor, you had to double quote your password if there was some special character such as $,{,... 
After my fix it wasn't neeeded anymore.

**Comment by dr-boss** [comment]
My big mistake. I did yesterday update of RPI with many docker containers and my routing table crash. The problem is no access from vissmann subsystem to dns resolver. Sorry, I send question before checking all on my site.
